fixed importing kmz and kml files due to linker stripping away properties from SharpKml.Core
error in AppCenter was:
System.TypeInitializationException: Type 'SharpKml.Dom.Description' does not have a default constructor Parameter name: type
    SharpKml.Base
    Parser.CreateElement ()
    SharpKml.Base
    Parser.Parse (System.Xml.XmlReader reader)
    SharpKml.Base
    Parser.Parse (System.IO.TextReader input, System.Boolean namespaces)
    SharpKml.Engine
    KmlFile.Parse (System.IO.TextReader input)
    SharpKml.Engine
    KmlFile.Load (System.IO.TextReader reader)
    SharpKml.Engine
    KmzFile.GetDefaultKmlFile ()
    WhereToFly.App.Geo.DataFormats.KmlDataFile
    WhereToFly.App.Geo.DataFormats.KmlDataFile..ctor (System.IO.Stream stream, System.String filename, System.Boolean isKml)
    WhereToFly.App.Geo.DataFormats
    GeoLoader.LoadGeoDataFile (System.IO.Stream stream, System.String filename)
    WhereToFly.App.Core
    OpenFileHelper.OpenFileAsync (System.IO.Stream stream, System.String filename)